-- RG REPORTES V5 + SUPABASE
-- Execute este SQL no SQL Editor do Supabase.
-- A tabela "reportes" que já criaste é aproveitada.

alter table public.reportes
  add column if not exists codigo text,
  add column if not exists ano integer,
  add column if not exists sequencia integer,
  add column if not exists data_hora timestamptz default now(),
  add column if not exists email_preparado boolean default false;

create table if not exists public.atualizacoes (
  id bigint generated by default as identity primary key,
  codigo text not null,
  ano integer not null,
  sequencia integer not null,
  data_iso date not null,
  data_display text,
  hora_inicial text not null,
  hora_final text not null,
  servico text,
  motivo text,
  observacoes text,
  estado text default 'Agendada',
  lembretes boolean default false,
  aviso3_enviado boolean default false,
  aviso1_enviado boolean default false,
  criado_em timestamptz default now()
);

alter table public.reportes enable row level security;
alter table public.atualizacoes enable row level security;

drop policy if exists "Utilizadores autenticados podem ver atualizacoes" on public.atualizacoes;
drop policy if exists "Utilizadores autenticados podem criar atualizacoes" on public.atualizacoes;
drop policy if exists "Utilizadores autenticados podem alterar atualizacoes" on public.atualizacoes;
drop policy if exists "Utilizadores autenticados podem apagar atualizacoes" on public.atualizacoes;

create policy "Utilizadores autenticados podem ver atualizacoes"
on public.atualizacoes for select to authenticated using (true);

create policy "Utilizadores autenticados podem criar atualizacoes"
on public.atualizacoes for insert to authenticated with check (true);

create policy "Utilizadores autenticados podem alterar atualizacoes"
on public.atualizacoes for update to authenticated using (true) with check (true);

create policy "Utilizadores autenticados podem apagar atualizacoes"
on public.atualizacoes for delete to authenticated using (true);

-- Corrige/garante defaults úteis na tabela reportes.
alter table public.reportes alter column estado set default 'Aguardar';
alter table public.reportes alter column data_hora set default now();
